<?php
  // Default information
  $g_theme["Author"] = "Sandy Pleyte"; // Author name
  $g_theme["Author_email"] = "sandy@ibuildings.nl";  // Author e-mail
  $g_theme["Description"] = "Blackbox";  // Theme description
  $g_theme["Version"] = "1.0";  // version number
  
  // some picture urls
  $g_theme["BgURL"] = "";    // Background url
  $g_theme["LogoURLl"] = "";  // Logo url
  
  // Font settings
  $g_theme["FontFamily"] = "Helvetica,Lucida,sans-serif"; // Font
  $g_theme["FontSize"] = "8"; // Font size in pt.
  $g_theme["FontWeight"] = "none"; 
  
  // Font settings for a block
  $g_theme["BlockFontFamily"] = "Helvetica,Lucida,sans-serif"; // Font
  $g_theme["BlockFontSize"] = "12"; // Font size in pt.
  $g_theme["BlockFontWeight"] = "none"; // FontWeight (bold) 

  // Body settings
  $g_theme["BgColor"] = "#707888"; // Background color
  $g_theme["FgColor"] = "#000000"; // text color
  
  // Link settings
  $g_theme["LinkColor"] = "#cccccc"; // link color
  $g_theme["VisitedColor"] = "#cccccc"; // Visited color
  $g_theme["HoverColor"] = "#cccccc"; // Hover color (IE4 Only)
  $g_theme["ActiveColor"] = "#cccccc"; // Active color (IE4 Only)

  // Table header settings
  $g_theme["TableHeaderFontFamily"] = "Helvetica,Lucida,sans-serif"; // Font
  $g_theme["TableHeaderFontSize"] = "12"; // Font size in pt.
  $g_theme["TableHeaderFontWeight"] = "Bold"; // FontWeight (bold) 
  $g_theme["TableHeaderBgColor"] = "#8b95a8"; // Table bgcolor;
  $g_theme["TableHeaderFgColor"] = "#000000"; // Table font color;
 
  // Table settings
  $g_theme["TableFontFamily"] = "Helvetica,Lucida,sans-serif"; // Font
  $g_theme["TableFontSize"] = "12"; // Font size in pt.
  $g_theme["TableFontWeight"] = "none"; // FontWeight (bold) 
  $g_theme["TableFgColor"] = "#000000"; // Table font color;

  // display settings 
  $g_theme["border"] = "1";
  $g_theme["BorderColor"] = "#000000";
  $g_theme["RowColor1"] ="#BCC2CE";
  $g_theme["RowColor2"] = "#707888";
  $g_theme["RowMouseOver"] = "#ccffcc";


?>
