<?php

  // Default information
  $g_theme["Author"] = "Paul Verhoeff"; // Author name
  $g_theme["Author_email"] = "paul@ibuildings.nl";  // Author e-mail
  $g_theme["Description"] = "RainyD";  // Theme description
  $g_theme["Version"] = "1.0";  // version number
  
  // some picture urls
  $g_theme["BgURL"] = "images/bg2.gif";    // Background url
  $g_theme["LogoURLl"] = "";  // Logo url
  
  // Font settings
  $g_theme["FontFamily"] = "Verdana,Arial,Helvetica"; // Font
  $g_theme["FontSize"] = "11"; // Font size in pt.
  $g_theme["FontWeight"] = "none"; 
  
  // Font settings for a block
  $g_theme["BlockFontFamily"] = "Verdana,Arial,Helvetica"; // Font
  $g_theme["BlockFontSize"] = "10"; // Font size in pt.
  $g_theme["BlockFontWeight"] = "none"; // FontWeight (bold) 
  
  // Body settings
  $g_theme["BgColor"] = "#b0b0c0"; // Background color

  $g_theme["FgColor"] = "#000000"; // text color
  
  // Link settings
  $g_theme["LinkColor"] = "#000000"; // link color
  $g_theme["VisitedColor"] = "#000000"; // Visited color
  $g_theme["HoverColor"] = "#006699"; // Hover color (IE4 Only)
  $g_theme["ActiveColor"] = "#000000"; // Active color (IE4 Only)

  // Table header settings
  $g_theme["TableHeaderFontFamily"] = "Helvetica,Arial"; // Font
  $g_theme["TableHeaderFontSize"] = "10"; // Font size in pt.
  $g_theme["TableHeaderFontWeight"] = "Bold"; // FontWeight (bold) 
  $g_theme["TableHeaderBgColor"] = "#aaaaaa"; // Table bgcolor;
  $g_theme["TableHeaderFgColor"] = "#000000"; // Table font color;
  $g_theme["TableHeaderbackground"] = "themes/images/header-bg.gif"; // Table background;

  // Table settings
  $g_theme["TableFontFamily"] = "Arial,Helvetica"; // Font
  $g_theme["TableFontSize"] = "10"; // Font size in pt.
  $g_theme["TableFontWeight"] = "none"; // FontWeight (bold)
  $g_theme["TableFgColor"] = "#000000"; // Table font color;

  //Display settings  
  $g_theme["border"] = "1";
  $g_theme["BorderColor"] = "#000000";
  $g_theme["RowColor1"] ="#ffffff";
  $g_theme["RowColor2"] = "#eeeeee";
?>
