<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be
   * included in the distribution.
   *
   * @package atk
   *
   * This file contains variables about this ATK version and the
   * state of the code such as development or stable.
   *
   * @copyright (c)2000-2010 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision$
   * $Id$
   */

  /**
   * The current atk version
   */
  $atk_version = "7.0";
  $atk_state   = "development";
?>
