<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be
   * included in the distribution.
   *
   * @package atk
   * @subpackage themes
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision$
   * $Id$
   */

  /**
   * Theme definition
   */
  $theme["highlight"] = "#D6DFF7";
  $theme["select"]    = "#D6DFF7";
  $theme["tabtype"] = "dhtml";
  $theme["modern_menu_compat"] = true;
  $theme['compatible_menus'] = array("modern");
?>
