<?php
  /** Merge of steelblue + stillblue for v7.1 by Antonio Gallo */

$theme["doctype"] = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"'."\n".'"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">';
$theme['compatible_menus'] = array('atk.menu.atkDropdownMenu');
$theme["highlight"] = "";
$theme["select"] = "";
$theme["basetheme"] = "steelblue";
$theme['useframes'] = false;
$theme['dispatcher'] = 'index.php';
$theme['menufile'] = 'index.php';
$theme['menu_params'] = "class='menulink'";
$theme["tabtype"] = "dhtml";

