<?php
// Achievo language file for Brazilian_portuguese.
// Generated by Achievo Translation Tool (20100804).
//
// Module: atk
// Language: Brazilian_portuguese (bp)
//
// Translated by:
//   See doc/AUTHORS
//
// If you want to add a new language to achievo, please translate this
// file and send it to translations@achievo.org
//
// To update an existing translation, mail an updated version to
// translations@achievo.org or request an account for the Achievo
// Translation Tool.
//
$bp = array(
    "above_maximum_value" => "Acima do valor m�ximo permitido",
    "access_denied" => "Acesso negado",
    "add" => "Adicionar",
    "addorcopy" => "Add or copy",
    // Missing string!!!
    "add_criterium" => "Adicionar",
    "admin" => "Administra��o",
    "administration_application" => "Aplicativo de Administra��o",
    "all" => "Tudo",
    "alphabeticchars" => "Caracteres alfab�ticos",
    "apply" => "Aplicar",
    "app_close" => "Fechar",
    "app_description" => "Bem-vindo a este aplicativo ATK.",
    "app_launcher" => "Lan�ador de aplicativo ATK",
    "app_reopen" => "Reiniciar",
    "app_shorttitle" => "ATKApp",
    "app_title" => "Aplicativo ATK",
    "apr" => "Abr",
    "april" => "Abril",
    "attributeedit" => "Update value",
    // Missing string!!!
    "attrib_delete_not_allowed" => "O campo '%s' n�o permite que o registro seja deletado. (%s)'",
    "aug" => "Ago",
    "august" => "Agosto",
    "auth_account_locked" => "Esta conta foi bloqueada. Tente uma conta diferente se poss�vel, ou contate o administrador do sistema.",
    "auth_max_loginattempts_exceeded" => "Voc� excedeu o n�mero de tentativas. Entrada no sistema est� desativada. Por favor contacte o administrador.",
    "auth_mismatch" => "Usu�rio e/ou senha est�(�o) incorreto(s). Por favor tente novamente.",
    "auth_missingusername" => "Por favor, entre com um nome de usu�rio primeiro.",
    "auth_no_server" => "Servidor n�o especificado. N�o � poss�vel altenticar (por favor consulte o administrador do sistema).",
    "auth_passwordmail_explanation" => "Voc� recebeu este e-mail porque esqueceu sua senha. Abaixo est�o seus dados de logion:",
    "auth_passwordmail_sent" => "Se o nome de usu�rio j� existir, uma nova senha ser&aacute; enviada para o e-mail correspondente.",
    "auth_passwordmail_subjectnew_password" => "Nova senha",
    "auth_unable_to_connect" => "N�o foi poss�vel conectar ao servidor para autentica��o (por favor consulte o administrador do sistema).",
    "autocomplete_minimum_chars" => "Enter a minimum of %d characters.",
    // Missing string!!!
    "autocomplete_no_results" => "No results found for the given search value.",
    // Missing string!!!
    "autocomplete_no_results_contains" => "No results found that contain the given search value.",
    // Missing string!!!
    "autocomplete_no_results_exact" => "No results found that exactly match the given search value.",
    // Missing string!!!
    "autocomplete_no_results_startswith" => "No results found that start with the given search value.",
    // Missing string!!!
    "available" => "Available",
    // Missing string!!!
    "back" => "Voltar",
    "back_to" => "Voltar para",
    "below_minimum_value" => "Abaixo do valor m�nimo permitido",
    "cancel" => "Cancelar",
    "cancel_edit" => "Cancel edit",
    // Missing string!!!
    "cannot create directory" => "N�o foi poss�vel criar diret�rio: ",
    "cannot make file" => "N�o foi poss�vel criar arquivo: ",
    "cannot_remove_file" => "N�o foi poss�vel remover arquivo!",
    "captcha_explain" => "Please fill in the displayed code",
    // Missing string!!!
    "charset" => "iso-8859-1",
    "check rights to" => "Por favor verifique se vo� tem os direitos apropriados para ",
    "check_all" => "Selecionar todos",
    "check_none" => "N�o selecionar nenhum",
    "clickheretoadd_postfix" => ".",
    "clickheretoadd_prefix" => "Clique para adicionar um novo ",
    "close" => "Fechar",
    "color" => "Cor",
    "colorcode" => "C�digo da cor",
    "colorpicker_selectcolor" => "Selecionar uma cor",
    "column" => "coluna",
    "column_asc" => "Ascendente",
    "column_desc" => "Descendente",
    "column_subtotal" => "Subtotal",
    "column_unsubtotal" => "Sem Subtotal",
    "confirm_delete" => "Voc� est� certo de que quer remover este �tem?",
    "confirm_delete_multi" => "Voc� est� certo de que quer remover estes �tens?",
    "content_wizard_finished" => "Wizard was finished successfully!",
    // Missing string!!!
    "copy" => "Copiar",
    "criterium_field" => "Campo",
    "criterium_mode" => "Modo",
    "criterium_value" => "Valor",
    "critical" => "Cr�tico",
    "datagrid_norecordsfound_general" => "No records found.",
    // Missing string!!!
    "datagrid_norecordsfound_search" => "No results found for the current search query.",
    // Missing string!!!
    "datagrid_summary" => "(Records [start] - [end] of [count])",
    // Missing string!!!
    "date_format_edit" => "j F Y",
    "date_format_view" => "j F Y",
    "db_access_denied_database" => "Usu�rio '%s' n�o tem direitos para o banco de dados '%s'",
    "db_access_denied_user" => "Usu�rio '%s' n�o pode se conectar ao banco de dados '%s'",
    "db_unknown_database" => "N�o foi poss�vel se conectar ao banco de dados '%s'",
    "db_unknown_host" => "N�o foi poss�vel encontrar o local '%s'",
    "dec" => "Dez",
    "december" => "Dezembro",
    "decimal_separator" => ",",
    "delete" => "Remover",
    "delimiter" => "Separador",
    "deselect_all" => "Desfazer sele��o",
    "document" => "Abrir documento",
    "edit" => "Editar",
    "editcopy" => "Editar c�pia",
    "email" => "Email",
    "enclosure" => "Delimitado por",
    "error" => "Erro",
    "error_attributeedit_default" => "An unknown error has occurred.",
    // Missing string!!!
    "error_attributeedit_noselectorset" => "Please select the records you wish to edit.",
    // Missing string!!!
    "error_attributeedit_update" => "An error occured when updating the selected records.",
    // Missing string!!!
    "error_attributeedit_validationfailed" => "This value is not allowed.",
    // Missing string!!!
    "error_captchafield" => "The given code is invalid, please try again",
    // Missing string!!!
    "error_copy_record" => "Unknown error copying record",
    // Missing string!!!
    "error_date_invalid" => "Data inv�lida",
    "error_fileexists" => "Arquivo j� existe no servidor. Por favor renomeie o arquivo.",
    "error_file_mime_type" => "Unsupported file uploaded please check your filetype or extension",
    // Missing string!!!
    "error_file_size" => "Arquivo muito grande",
    "error_file_unknown" => "Erro desconhecido durante upload do arquivo",
    "error_format_mismatch" => "O elemento na posi��o %d n�o parece seguir o formato desejado",
    "error_formdataerror" => "Falha ao gravar pela seguinte raz�o: ",
    "error_iconv_not_install" => "iconv module don't install in your system, but it needs for right functionality",
    // Missing string!!!
    "error_invalid_email" => "Endere�o de e-mail inv�lido",
    "error_node_action_access_denied" => "Desculpe, voc� n�o tem permiss�o para efetuar esta a��o.",
    "error_notnumeric" => "Valor n�o � um n�mero",
    "error_not_a_valid_ip" => "This is not a valid IP address. An IP address consists of 4 numbers between 0 and 255.",
    // Missing string!!!
    "error_obligatoryfield" => "Este campo � obrigat�rio",
    "error_password_incorrect" => "A senha que voc� digitou est� errada!",
    "error_password_invalid" => "A senha que voc� digitou n�o � uma senha v�lida!",
    "error_password_nomatch" => "As senhas fornecidas n�o parecem ser a mesm.",
    "error_primarykey_exists" => "J� existe um registro com esta chave",
    "error_tab" => "ver",
    "error_tag_illegalvalue" => "A tag may not contain HTML or linefeeds.",
    // Missing string!!!
    "error_uniquefield" => "O valor para este campo precisa ser �nico",
    "error_uniquefieldset" => "O valor para a combina��o desses campos deve ser �nico",
    "error_unkown_domain" => "Dom�nio desconhecido",
    "explain_session_expired" => "Sua sess�o expirou. Isso ocorre se o aplicativo fica inativo por um certo per�odo de tempo. Voc� pode continuar seu trabalho entrando no sistema novamente.",
    "export" => "Exportar",
    "export_config_explanation" => "Selecione as opcoes para exporta��o tipo CSV.",
    "export_generatetitlerow" => "Titulo da linha",
    "export_selectcolumns" => "Selecione as colunas a exportar",
    "export_selections" => "Standard selections",
    // Missing string!!!
    "export_selections_name" => "Standard selections name",
    // Missing string!!!
    "feb" => "Fev",
    "february" => "Fevereiro",
    "feedback" => "Feedback",
    "feedback_delete_cancelled" => "O �tem n�o foi removido.",
    "feedback_delete_failed" => "O �tem n�o p�de ser removido.",
    "feedback_delete_success" => "O �tem foi removido com sucesso.",
    "feedback_edit_failed" => "Editing is not possible. Item doesn\'t exist (anymore).",
    // Missing string!!!
    "feedback_import_failed" => "O arquivo n�o p�de ser importado",
    "feedback_save_cancelled" => "O �tem n�o foi adicionado.",
    "feedback_save_failed" => "O �tem n�o p�de ser adicionado.",
    "feedback_save_success" => "O �tem foi adicionado com sucesso.",
    "feedback_update_cancelled" => "As mudan�as n�o foram gravadas.",
    "feedback_update_failed" => "As mudan�as n�o puderam ser gravadas.",
    "feedback_update_success" => "As mudan�as foram aplicadas com sucesso.",
    "field_obligatory" => "Este campo � obrigat�rio",
    "filecontent" => "Conte�do",
    "filename" => "Nome do arquivo",
    "filename_invalid" => "Esse nome de arquivo n�o � v�lido",
    "file_exists" => "J� existe um arquivo com este nome",
    "file_not_exist" => "O arquivo n�o existe",
    "finish" => "Finish",
    // Missing string!!!
    "forget_criteria" => "Remover a pesquisa selecionada",
    "fri" => "Sex",
    "friday" => "Sexta-feira",
    "fsa_pleasemakeselection" => "Mais de uma ocorr�ncia foi encontrada. Por favor fa�a sua sele��o.",
    "help" => "Ajuda",
    "import" => "Importar dados",
    "import_allfield" => "Usar valor de f�brica para os atributos (por exemplo, se a coluna estiver ausente no arquivo CSV)",
    "import_analyse" => "Analisar novamente",
    "import_detectedcolumns" => "Detectar n�mero de colunas",
    "import_detectedrows" => "N�mero de linhas detectadas",
    "import_doupdate" => "Tentar atualizar registros existentes",
    "import_error_allfieldnocorrectdata" => "O campo para uso em todos os registros n�o cont�m dados v�lidos",
    "import_error_fieldisobligatory" => "O pr�ximo campo � exigido e deve conter dados",
    "import_error_fieldsareobligatory" => "Os pr�ximos campos s�o exigidos e devem conter dados",
    "import_error_fieldsusedtwice" => "Os pr�ximos campos s�o usados duas vezes",
    "import_error_fieldusedtwice" => "O pr�ximo campo � usado duas vezes",
    "import_field" => "Campo",
    "import_ignorecolumn" => "Ignore esta coluna",
    "import_import" => "Importar",
    "import_importedreminder" => "O arquivo j� foi importado, entretanto erros foram detectados nas seguintes linhas, as quais n�o foram adicionadas (atualizadas)",
    "import_nonunique_identifier" => "Identificador n�o-�nico encontrado no registro onde identificador � %s",
    "import_onfalseidentifier" => "Inserir e continuar no caso de identificador falso (2 registros para a mesma chave)",
    "import_relation_value_failed" => "Do campo '%s' foi encontrado, na linha %s, o valor '%s', entretanto este n�o � um valor �nico para esta rela��o",
    "import_sample" => "Exemplo de arquivo CSV",
    "import_skipfirstrow" => "Pular a primeira linha? (linha de cabe�alho)",
    "import_update_key" => "Quando atualizando, usar este campo para identificar que registros atualizar",
    "import_upload" => "Enviar arquivo",
    "import_upload_explanation" => "Enviar um arquivo de texto com dados a importar para o banco de dados.",
    "import_validatefirst" => "N�o validar antes de importar",
    "intro_addorcopy" => "Do you want to create a new record or copy an existing record?",
    // Missing string!!!
    "invalid_relative_url" => "Invalid relative URL, please use this format: '/mysite/guestbook'",
    // Missing string!!!
    "invalid_url_anchor" => "Invalid URL anchor, please use this format: '#internal_bookmark'",
    // Missing string!!!
    "invert_selection" => "Inverter sele��o",
    "in_use_by" => "In use by",
    // Missing string!!!
    "jan" => "Jan",
    "january" => "Janeiro",
    "jul" => "Jul",
    "july" => "Julho",
    "jun" => "Jun",
    "june" => "Junho",
    "language_de" => "Alem�o",
    "language_en" => "Ingl�s",
    "language_fr" => "Franc�s",
    "language_nl" => "Holand�s",
    "language_pl" => "Polish",
    // Missing string!!!
    "language_sp" => "Spanish",
    // Missing string!!!
    "list_null_value" => "Vazio (sem valor)",
    "list_null_value_obligatory" => "(Select a value...)",
    // Missing string!!!
    "load_criteria" => "Ler pesquisa gravada",
    "lock_expired" => "Os �tens que voc� abriu n�o est�o acess�veis por voc� exclusivamente. Isso pode ter v�rias raz�es, a mais comum � que voc� n�o o tenha salvo por um longo per�odo de tempo. Voc� pode salvar seu trabalho, mas � poss�vel que os �tens estejam atualmente bloqueados por um outro usu�rio.",
    "lock_info_line" => "[user_id] (ip: [user_ip]) since [lock_date]",
    // Missing string!!!
    "lock_locked" => "Os �tens selecionados n�o est�o acess�veis porque outro usu�rio os bloqueou.",
    "logged_in_as" => "No sistema como",
    "login" => "Entrar",
    "login_failed" => "Entrada no sistema falhou",
    "login_form" => "Entrar no Sistema",
    "logout" => "Sair",
    "lose_changes_warning" => "If you navigate away from this page, all your changes will be lost.",
    // Missing string!!!
    "lowerchars" => "caracteres min�sculos",
    "mar" => "Mar",
    "march" => "Mar�o",
    "may" => "Maio",
    "menu" => "Menu",
    "menu_main" => "Principal",
    "mon" => "Seg",
    "monday" => "Segunda-feira",
    "multiselect" => "Multiselect",
    // Missing string!!!
    "new" => "Novo",
    "next" => "Pr�ximo",
    "no" => "N�o",
    "none" => "Nenhum",
    "nov" => "Nov",
    "november" => "Novembro",
    "no_color_selected" => "Cor n�o selecionada",
    "no_copyable_records" => "no copyable records",
    // Missing string!!!
    "no_records_to_import" => "No records found that needed to be imported.",
    // Missing string!!!
    "no_results_found" => "Nenhum resultado encontrado",
    "no_valid_directory" => "Este n�o � um diret�rio v�lido",
    "numbers" => "n�meros",
    "oct" => "Out",
    "october" => "Outubro",
    "open" => "Abrir",
    "or" => "Ou",
    "password" => "Senha",
    "password_again" => "Novamente",
    "password_current" => "Atual",
    "password_forgotten" => "Esqueceu a senha",
    "password_hidden" => "*****",
    "password_incorrect" => "A senha que voc� digitou n�o estava correta!",
    "password_invalid" => "A senha fornecida n�o � uma senha v�lida.",
    "password_new" => "Nova",
    "permission_denied" => "Desculpe, Voc� n�o tem permiss�o para realizar esta a��o",
    "previous" => "Anterior",
    "recordlistsummary" => "Record [start]-[end] out of [count]",
    // Missing string!!!
    "relogin" => "Entrar novamente",
    "remove_criterium" => "Remover",
    "remove_current_file" => "Remover arquivo atual",
    "replace_by" => "Substituir por",
    "reset_criteria" => "Nova pesquisa",
    "restricted_delete_error" => "H� informa��es detalhadas abaixo deste registro que precisam ser removidas primeiro.",
    "sat" => "S�b",
    "saturday" => "S�bado",
    "save" => "Gravar",
    "saveandaddnew" => "Save and add new",
    // Missing string!!!
    "saveandclose" => "Gravar e fechar",
    "saveandedit" => "Save and edit",
    // Missing string!!!
    "saveandnext" => "Gravar e Pr�ximo",
    "save_criteria" => "Salvar pesquisa como",
    "save_export_selection" => "Save selection",
    // Missing string!!!
    "search" => "Busca",
    "search_all" => "Buscar todos",
    "search_and" => "Com todos os crit�rios",
    "search_between" => "Busca entre dois valores",
    "search_exact" => "Busca pela express�o exata",
    "search_extended" => "Extendido",
    "search_greaterthan" => "Busca por valores maiores que",
    "search_greaterthanequal" => "Busca por valores maiores que ou iguais a",
    "search_lessthan" => "Busca por valores menores que",
    "search_lessthanequal" => "Busca por valores menores que ou iguais a",
    "search_mode" => "Modo de busca",
    "search_none" => "Nothing selected",
    // Missing string!!!
    "search_or" => "Qualquer dos crit�rios",
    "search_regexp" => "Busca com express�o regular (avan�ado)",
    "search_soundex" => "Busca por um texto que soe familiar",
    "search_substring" => "Busca por um trecho de texto",
    "search_wildcard" => "Busca com curingas (*)",
    "select" => "Selecionar",
    "selected" => "Selected",
    // Missing string!!!
    "selection" => "Sele��o",
    "select_a" => "Selecionar um",
    "select_all" => "Selecionar todos",
    "select_invert" => "Inverter sele��o",
    "select_none" => "Nenhum",
    "self" => "Pr�prio",
    "sep" => "Set",
    "september" => "Setembro",
    "settings" => "Configura��o",
    "show" => "Show",
    // Missing string!!!
    "smartsearch" => "Pesquisa inteligente",
    "sort" => "Ordem",
    "specialchars" => "caracteres especiais",
    "steelblue" => "SteelBlue",
    // Missing string!!!
    "submit" => "Enviar",
    "successfully_imported_one_record" => "Successfully imported 1 record.",
    // Missing string!!!
    "successfully_imported_x_records" => "Successfully imported %d records.",
    // Missing string!!!
    "sun" => "Dom",
    "sunday" => "Domingo",
    "tab_default" => "Geral",
    "the_password_should_at_least_contain_%d_%s" => "A senha precisa ter pelo menos %d %s.",
    "the_password_should_be_at_least_%d_characters_long" => "A senha precisa ter pelo menos %d caracteres.",
    "thousands_separator" => ".",
    "thu" => "Qui",
    "thursday" => "Quinta-feira",
    "timezone_utc_+0000" => "(UTC) Casablanca, Greenwich Mean Time, London",
    // Missing string!!!
    "timezone_utc_+0100" => "(UTC+01:00) Amsterdam, Berlin, Rome, Paris",
    // Missing string!!!
    "timezone_utc_+0200" => "(UTC+02:00) Athens, Beirut, Istanbul, Minsk",
    // Missing string!!!
    "timezone_utc_+0300" => "(UTC+03:00) Baghdad, Kuwait, Riyadh, Moscow",
    // Missing string!!!
    "timezone_utc_+0400" => "(UTC+04:00) Abu Dhabi, Kabul",
    // Missing string!!!
    "timezone_utc_+0500" => "(UTC+05:00) New Delhi, Mumbai, Kathmandu",
    // Missing string!!!
    "timezone_utc_+0600" => "(UTC+06:00) Novosibirsk, Dhaka, Sri Jayawardenepura",
    // Missing string!!!
    "timezone_utc_+0700" => "(UTC+07:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk",
    // Missing string!!!
    "timezone_utc_+0800" => "(UTC+08:00) Beijing, Hong Kong, Ulaan Bataar",
    // Missing string!!!
    "timezone_utc_+0900" => "(UTC+09:00) Osaka, Sapporo, Tokyo, Seoul",
    // Missing string!!!
    "timezone_utc_+1000" => "(UTC+10:00) Brisbane, Melbourne, Sydney",
    // Missing string!!!
    "timezone_utc_+1100" => "(UTC+11:00) Solomon Is., Magadan",
    // Missing string!!!
    "timezone_utc_+1200" => "(UTC+12:00) Auckland, Wellington, Fiji",
    // Missing string!!!
    "timezone_utc_+1300" => "(UTC+13:00) Nuku'alofa",
    // Missing string!!!
    "timezone_utc_-0100" => "(UTC-01:00) Azores, Cape Verde Is.",
    // Missing string!!!
    "timezone_utc_-0200" => "(UTC-02:00) Mid-Atlantic",
    // Missing string!!!
    "timezone_utc_-0300" => "(UTC-03:00) Brasilia, Buenos Aires, Greenland",
    // Missing string!!!
    "timezone_utc_-0400" => "(UTC-04:00) Atlantic Time (Canada), Santiago",
    // Missing string!!!
    "timezone_utc_-0500" => "(UTC-05:00) Bogota, Lima, Quito, Eastern Time (US & Canada)",
    // Missing string!!!
    "timezone_utc_-0600" => "(UTC-06:00) Central America, Central Time (US & Canada)",
    // Missing string!!!
    "timezone_utc_-0700" => "(UTC-07:00) Arizona, Mountain Time (US & Canada)",
    // Missing string!!!
    "timezone_utc_-0800" => "(UTC-08:00) Pacific Time (US & Canada); Tijuna",
    // Missing string!!!
    "timezone_utc_-0900" => "(UTC-09:00) Alaska",
    // Missing string!!!
    "timezone_utc_-1000" => "(UTC-10:00) Hawaii",
    // Missing string!!!
    "timezone_utc_-1100" => "(UTC-11:00) Midway Island, Samoa",
    // Missing string!!!
    "timezone_utc_-1200" => "(UTC-12:00) International Date Line West",
    // Missing string!!!
    "title_delete" => "Confirmar remo��o",
    "title_multiselect" => "Multiselect",
    // Missing string!!!
    "title_select" => "Sele��o",
    "title_session_expired" => "Sess�o expirou",
    "title_wizard_finished" => "Wizard finished",
    // Missing string!!!
    "today" => "Hoje",
    "tue" => "Ter",
    "tuesday" => "Tur�a-feira",
    "unknown_error" => "Erro desconhecido",
    "unselect" => "Remover sele��o",
    "until" => "enquanto",
    "update" => "Atualizar",
    "upperchars" => "caracteres mai�sculos",
    "username" => "Usu&aacute;rio",
    "view" => "Ver",
    "view_all" => "Ver todos",
    "wed" => "Qua",
    "wednesday" => "Quarta-feira",
    "with_selected" => "Com os selecionados",
    "ww_sourcemode" => "Modo c�digo-fonte",
    "ww_visualmode" => "Modo visual",
    "wysiwyg_delete_cell" => "Remover c�lula",
    "wysiwyg_delete_col" => "Remover coluna",
    "wysiwyg_delete_row" => "Remover linha",
    "wysiwyg_fontface" => "Fonte",
    "wysiwyg_fontsize" => "Pt",
    "wysiwyg_insert_cell" => "Inserir c�lula",
    "wysiwyg_insert_col" => "Inserir coluna",
    "wysiwyg_insert_row" => "Inserir linha",
    "wysiwyg_insert_table" => "Inserir tabela",
    "wysiwyg_merge_cell" => "Mesclar c�lulas",
    "wysiwyg_split_cell" => "Dividir c�lulas",
    "yes" => "Sim",
);