<?php
  // Default information
  $g_theme["Author"] = "Sandy Pleyte"; // Author name
  $g_theme["Author_email"] = "sandy@ibuildings.nl";  // Author e-mail
  $g_theme["Description"] = "Ananda";  // Description of the theme
  $g_theme["Version"] = "1.5";  // version number
  
  // some pircture urls
  $g_theme["BgURL"] = "";    // Background url
  $g_theme["LogoURLl"] = "";  // Logo url
  
  // Font settings
  $g_theme["FontFamily"] = "Verdana,Arial,Helvetica"; // Font
  $g_theme["FontSize"] = "8"; // Font size in pt.
  $g_theme["FontWeight"] = "none"; 
  
  // Font settings for a block
  $g_theme["BlockFontFamily"] = "Verdana,Arial,Helvetica"; // Font
  $g_theme["BlockFontSize"] = "10"; // Font size in pt.
  $g_theme["BlockFontWeight"] = "none"; // FontWeight (bold) 
  
  // Body settings
  $g_theme["BgColor"] = "#ffffff"; // Background color
  $g_theme["FgColor"] = "#000000"; // text color

  // Link settings
  $g_theme["LinkColor"] = "#006896"; // link color
  $g_theme["HoverColor"] = "#000000"; // Hover color
  $g_theme["VisitedColor"] = "#000000"; // Visited color
  $g_theme["ActiveColor"] = "#000000"; // Active color (IE4 Only)

  // Table header settings
  $g_theme["TableHeaderFontFamily"] = "Verdana,Arial,Helvetica"; // Font
  $g_theme["TableHeaderFontSize"] = "10"; // Font size in pt.
  $g_theme["TableHeaderFontWeight"] = "Bold"; // FontWeight (bold) 
  $g_theme["TableHeaderBgColor"] = "#E8D6A6"; // Table bgcolor;
  $g_theme["TableHeaderFgColor"] = "#000000"; // Table font color;
 
  // Table settings
  $g_theme["TableFontFamily"] = "Verdana,Arial,Helvetica"; // Font
  $g_theme["TableFontSize"] = "10"; // Font size in pt.
  $g_theme["TableFontWeight"] = "none"; // FontWeight (bold) 
  $g_theme["TableFgColor"] = "#000000"; // Table font color;

// display settings 
  $g_theme["border"] = "1";
  $g_theme["BorderColor"] = "#827A74";
  $g_theme["RowColor1"] ="#EBE6D9";
  $g_theme["RowColor2"] = "#ffffff";


?>
