<?php
// Achievo language file for Finnish.
// Generated by Achievo Translation Tool (20100804).
//
// Module: atk
// Language: Finnish (fi)
//
// Translated by:
//   See doc/AUTHORS
//
// If you want to add a new language to achievo, please translate this
// file and send it to translations@achievo.org
//
// To update an existing translation, mail an updated version to
// translations@achievo.org or request an account for the Achievo
// Translation Tool.
//
return [
    'above_maximum_value' => 'Above the maximum allowed value',
    // Missing string!!!
    'access_denied' => 'Access denied',
    // Missing string!!!
    'add' => 'Lisää',
    // Missing string!!!
    'add_criterium' => 'Add',
    // Missing string!!!
    'admin' => 'Ylläpito',
    // Missing string!!!
    'all' => 'All',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'app_description' => 'Tervetuloa ATK-Ohjelmistoon.',
    // Missing string!!!
    // Missing string!!!
    'app_shorttitle' => 'ATKApp',
    'app_title' => 'ATK-Ohjelmisto',
    'apr' => 'Apr',
    // Missing string!!!
    'april' => 'April',
    // Missing string!!!
    'attrib_delete_not_allowed' => "Field '%s' does not allow the record to be deleted. (%s)'",
    // Missing string!!!
    'aug' => 'Aug',
    // Missing string!!!
    'august' => 'August',
    'auth_account_locked' => 'This account has been locked. Try a different account if possible, or contact your system administrator.',
    'auth_max_loginattempts_exceeded' => 'Too many retries. Login has been disabled. Please contact your system administrator.',
    'auth_mismatch' => 'Username and/or password are incorrect. Please try again.',
    'auth_missingusername' => 'Please enter a username first.',
    // Missing string!!!
    'auth_no_server' => 'No server specified. No authentication possible (please consult your system administrator).',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'auth_unable_to_connect' => 'Unable to connect to server for authentication (please consult your system administrator).',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'available' => 'Available',
    // Missing string!!!
    'back' => 'Takaisin',
    // Missing string!!!
    'cancel' => 'Peruuta',
    'cancel_edit' => 'Cancel edit',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'charset' => 'UTF-8',
    // Missing string!!!
    'check_all' => 'Select all',
    'check_none' => 'Select none',
    'close' => 'Sulje',
    // Missing string!!!
    // Missing string!!!
    'column' => 'column',
    // Missing string!!!
    'column_asc' => 'Up',
    // Missing string!!!
    'column_desc' => 'Down',
    // Missing string!!!
    'column_subtotal' => 'Subtotal',
    // Missing string!!!
    'column_unsubtotal' => 'No Subt.',
    // Missing string!!!
    'confirm_delete' => 'Oletko varma että haluat poistaa?',
    // Missing string!!!
    // Missing string!!!
    'copy' => 'Copy',
    'criterium_field' => 'Field',
    // Missing string!!!
    'criterium_mode' => 'Mode',
    // Missing string!!!
    'criterium_value' => 'Value',
    // Missing string!!!
    'critical' => 'Critical',
    // Missing string!!!
    'datagrid_norecordsfound_general' => 'No records found.',
    // Missing string!!!
    'datagrid_norecordsfound_search' => 'No results found for the current search query.',
    // Missing string!!!
    'datagrid_summary' => '(Records [start] - [end] of [count])',
    // Missing string!!!
    'date_format_edit' => 'j F Y',
    // Missing string!!!
    'date_format_view' => 'j F Y',
    // Missing string!!!
    'db_access_denied_database' => "User '%s' has no rights for database '%s'",
    // Missing string!!!
    'db_access_denied_user' => "User'%s' can't connect with database '%s'",
    // Missing string!!!
    'db_unknown_database' => "Can't connect to database '%s'",
    // Missing string!!!
    'db_unknown_host' => "Can't find host '%s'",
    // Missing string!!!
    'dec' => 'Dec',
    // Missing string!!!
    'december' => 'December',
    'decimal_separator' => '.',
    // Missing string!!!
    'delete' => 'Poista',
    'delimiter' => 'Delimiter',
    // Missing string!!!
    'deselect_all' => 'Deselect all',
    // Missing string!!!
    'edit' => 'Muokkaa',
    'editcopy' => 'Edit copy',
    // Missing string!!!
    'email' => 'E-mail',
    // Missing string!!!
    'enclosure' => 'Enclosure',
    // Missing string!!!
    'error' => 'Virhe',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'error_date_invalid' => 'Invalid date',
    // Missing string!!!
    // Missing string!!!
    'error_file_mime_type' => 'Unsupported file uploaded please check your filetype or extension',
    // Missing string!!!
    'error_file_size' => 'File is too big',
    // Missing string!!!
    'error_file_unknown' => 'Unknown error during upload of file',
    // Missing string!!!
    'error_format_mismatch' => 'The element at position %d does not match the desired format (%s)',
    // Missing string!!!
    'error_formdataerror' => 'Tallennuksessa tapahtui virhe kyseisen syyn takia: ',
    'error_iconv_not_install' => "iconv module don't install in your system, but it needs for right functionality",
    // Missing string!!!
    'error_invalid_email' => 'Invalid e-mail address',
    // Missing string!!!
    'error_node_action_access_denied' => 'Sorry, you do not have permission to perform this action.',
    // Missing string!!!
    'error_notnumeric' => 'Value should be numeric',
    // Missing string!!!
    'error_not_a_valid_ip' => 'This is not a valid IP address. An IP address consists of 4 numbers between 0 and 255.',
    // Missing string!!!
    'error_obligatoryfield' => 'Tämä kenttä tarvitaan',
    'error_password_incorrect' => 'The password you entered is incorrect!',
    // Missing string!!!
    // Missing string!!!
    'error_password_nomatch' => 'Salasanat eivät täsmää.',
    'error_primarykey_exists' => 'A record with this key already exists',
    'error_tab' => 'see',
    // Missing string!!!
    // Missing string!!!
    'error_uniquefield' => 'Tämän kentän arvo tulee olla ainutlaatuinen',
    'error_uniquefieldset' => 'The values for the combination of these fields must be unique',
    // Missing string!!!
    'error_unkown_domain' => 'Unkown domain',
    // Missing string!!!
    'explain_session_expired' => 'Your session has expired. This happens if the application is inactive for a certain amount of time. You can continue work by logging in again.',
    'export' => 'Export',
    // Missing string!!!
    'export_config_explanation' => 'Please select the options for the CSV export.',
    // Missing string!!!
    'export_generatetitlerow' => 'Include a title row',
    // Missing string!!!
    'export_selectcolumns' => 'Select which columns to export',
    // Missing string!!!
    'export_selections' => 'Standard selections',
    // Missing string!!!
    'export_selections_name' => 'Standard selections name',
    // Missing string!!!
    'feb' => 'Feb',
    // Missing string!!!
    'february' => 'February',
    'feedback' => 'Feedback',
    // Missing string!!!
    'feedback_delete_cancelled' => 'The item has not been deleted.',
    // Missing string!!!
    'feedback_delete_failed' => 'The item could not be deleted.',
    // Missing string!!!
    'feedback_delete_success' => 'The item has been deleted.',
    // Missing string!!!
    'feedback_edit_failed' => "Editing is not possible. Item doesn\'t exist (anymore).",
    // Missing string!!!
    'feedback_import_failed' => 'File can not be imported',
    // Missing string!!!
    'feedback_save_cancelled' => 'The item has not been added.',
    // Missing string!!!
    'feedback_save_failed' => 'The item could not be added.',
    // Missing string!!!
    'feedback_save_success' => 'The item has been added.',
    // Missing string!!!
    'feedback_update_cancelled' => 'Changes have not been saved.',
    // Missing string!!!
    'feedback_update_failed' => 'The changes could not be saved.',
    // Missing string!!!
    'feedback_update_success' => 'The changes have been saved.',
    // Missing string!!!
    'filecontent' => 'Content',
    'filename' => 'Filename',
    'filename_invalid' => 'This filename is invalid',
    'file_exists' => 'A file with this name already exists',
    'file_not_exist' => 'Tiedostoa ei ole',
    // Missing string!!!
    'forget_criteria' => 'Remove selected search',
    // Missing string!!!
    'fri' => 'Fri',
    'friday' => 'Friday',
    // Missing string!!!
    'fsa_pleasemakeselection' => 'More than one match was found. Please make a selection.',
    // Missing string!!!
    'help' => 'Help',
    'import' => 'Import data',
    // Missing string!!!
    'import_allfield' => 'Use default value for one of the attributes (e.g. if the column is absent in the CSV file)',
    // Missing string!!!
    'import_analyse' => 'Analyse again',
    // Missing string!!!
    'import_detectedcolumns' => 'Detected number of columns',
    // Missing string!!!
    'import_detectedrows' => 'Detected number of rows',
    // Missing string!!!
    'import_doupdate' => 'Try to update existing records',
    // Missing string!!!
    'import_error_allfieldnocorrectdata' => "The field for use in every record ('%s') does not contain valid data (%s)",
    // Missing string!!!
    'import_error_fieldisobligatory' => 'The following field should be mapped to a column',
    // Missing string!!!
    'import_error_fieldsareobligatory' => 'The following fields should be mapped to a column',
    // Missing string!!!
    'import_error_fieldsusedtwice' => 'The following fields are used more than once',
    // Missing string!!!
    'import_error_fieldusedtwice' => 'The following field is used more than once',
    // Missing string!!!
    'import_field' => 'Field',
    // Missing string!!!
    'import_ignorecolumn' => 'Ignore this column',
    // Missing string!!!
    'import_import' => 'Import',
    // Missing string!!!
    'import_importedreminder' => 'The file has already been imported, however there were errors detected in the following rows, these were not added/updated',
    // Missing string!!!
    'import_nonunique_identifier' => 'Non-unique identifier found in record where identier is %s',
    // Missing string!!!
    'import_onfalseidentifier' => 'Insert and continue in case of false identifier (2 records for the same key)',
    // Missing string!!!
    'import_relation_value_failed' => "Of the field '%s' has been found, on line %s, the value '%s', however this is not a unique value for this relation",
    // Missing string!!!
    'import_sample' => 'Sample from csv-file',
    // Missing string!!!
    'import_skipfirstrow' => 'Skip first line? (header row)',
    // Missing string!!!
    'import_update_key' => 'When updating, use this field to identify which record to update',
    // Missing string!!!
    'import_upload' => 'Upload',
    // Missing string!!!
    'import_upload_explanation' => 'Upload a textfile with data to import into the database.',
    // Missing string!!!
    'import_validatefirst' => 'Do not validate before importing',
    // Missing string!!!
    // Missing string!!!
    'invalid_relative_url' => "Invalid relative URL, please use this format: '/mysite/guestbook'",
    // Missing string!!!
    'invalid_url_anchor' => "Invalid URL anchor, please use this format: '#internal_bookmark'",
    // Missing string!!!
    'invert_selection' => 'Invert selection',
    'in_use_by' => 'In use by',
    // Missing string!!!
    'jan' => 'Jan',
    // Missing string!!!
    'january' => 'January',
    'jul' => 'Jul',
    // Missing string!!!
    'july' => 'July',
    'jun' => 'Jun',
    // Missing string!!!
    'june' => 'June',
    'language_de' => 'Saksa',
    'language_en' => 'English',
    // Missing string!!!
    'language_fr' => 'French',
    // Missing string!!!
    'language_nl' => 'Hollanti',
    'language_pl' => 'Polish',
    // Missing string!!!
    'language_sp' => 'Spanish',
    // Missing string!!!
    'list_null_value' => 'No value',
    // Missing string!!!
    'list_null_value_obligatory' => '(Select a value...)',
    // Missing string!!!
    'load_criteria' => 'Load saved search',
    // Missing string!!!
    // Missing string!!!
    'lock_info_line' => '[user_id] (ip: [user_ip]) since [lock_date]',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'login' => 'Login',
    'login_form' => 'Login',
    // Missing string!!!
    'lose_changes_warning' => 'If you navigate away from this page, all your changes will be lost.',
    // Missing string!!!
    // Missing string!!!
    'mar' => 'Mar',
    // Missing string!!!
    'march' => 'March',
    'may' => 'May',
    'menu' => 'Valikko',
    'menu_main' => 'Main',
    'mon' => 'Mon',
    'monday' => 'Monday',
    // Missing string!!!
    // Missing string!!!
    'new' => 'New',
    // Missing string!!!
    'next' => 'Seuraava',
    'no' => 'Ei',
    'none' => 'None',
    // Missing string!!!
    'nov' => 'Nov',
    // Missing string!!!
    'november' => 'November',
    // Missing string!!!
    // Missing string!!!
    'no_records_to_import' => 'No records found that needed to be imported.',
    // Missing string!!!
    'no_results_found' => 'No results found',
    // Missing string!!!
    'no_valid_directory' => 'Kyseistä hakemistoa ei ole',
    'numbers' => 'numbers',
    // Missing string!!!
    'oct' => 'Oct',
    // Missing string!!!
    'october' => 'October',
    'open' => 'Open',
    // Missing string!!!
    'or' => 'Or',
    // Missing string!!!
    'password' => 'Password',
    'password_again' => 'Uudelleen',
    'password_current' => 'Nykyinen',
    // Missing string!!!
    'password_hidden' => '*****',
    'password_incorrect' => 'Antamasi salasana on väärä!',
    'password_new' => 'Uusi',
    'recordlistsummary' => 'Record [start]-[end] out of [count]',
    // Missing string!!!
    'relogin' => 'Log in again',
    // Missing string!!!
    'remove_criterium' => 'Remove',
    // Missing string!!!
    'remove_current_file' => 'Poista kyseinen tiedosto',
    // Missing string!!!
    'reset_criteria' => 'New search',
    // Missing string!!!
    'restricted_delete_error' => 'There is detail information below this record that needs to be deleted first.',
    // Missing string!!!
    'sat' => 'Sat',
    'saturday' => 'Saturday',
    // Missing string!!!
    'save' => 'Tallenna',
    'saveandaddnew' => 'Save and add new',
    // Missing string!!!
    'saveandclose' => 'Tallenna ja sulje',
    'saveandedit' => 'Save and edit',
    // Missing string!!!
    'saveandnext' => 'Save and next',
    // Missing string!!!
    'save_criteria' => 'Save search as',
    // Missing string!!!
    'save_export_selection' => 'Save selection',
    // Missing string!!!
    'search' => 'Etsi',
    'search_all' => 'Etsi kaikki',
    'search_and' => 'Match all criteria',
    // Missing string!!!
    'search_between' => 'Search between two values',
    // Missing string!!!
    'search_exact' => 'Search for an exact match',
    'search_extended' => 'Extended',
    'search_greaterthan' => 'Search for value bigger than',
    // Missing string!!!
    'search_greaterthanequal' => 'Search for value bigger than or equal to',
    // Missing string!!!
    'search_lessthan' => 'Search for value smaller than',
    // Missing string!!!
    'search_lessthanequal' => 'Search for value smaller than or equal to',
    // Missing string!!!
    'search_mode' => 'Searchmode',
    'search_none' => 'Nothing selected',
    // Missing string!!!
    'search_or' => 'Match any criteria',
    // Missing string!!!
    'search_regexp' => 'Search with a regular expression (advanced)',
    'search_soundex' => 'Search for a string that sounds similar',
    'search_substring' => 'Search for a substring',
    'search_wildcard' => 'Search with wildcards (*)',
    'select' => 'Valitse',
    'selected' => 'Selected',
    // Missing string!!!
    'selection' => 'Selection',
    // Missing string!!!
    'select_a' => 'Select',
    // Missing string!!!
    'select_all' => 'Select all',
    'select_invert' => 'Invert selection',
    'select_none' => 'None',
    'self' => 'Self',
    // Missing string!!!
    'sep' => 'Sep',
    // Missing string!!!
    'september' => 'September',
    'settings' => 'Settings',
    // Missing string!!!
    'show' => 'Show',
    // Missing string!!!
    'smartsearch' => 'Smart search',
    // Missing string!!!
    'sort' => 'Sort',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'submit' => 'Go',
    'successfully_imported_one_record' => 'Successfully imported 1 record.',
    // Missing string!!!
    'successfully_imported_x_records' => 'Successfully imported %d records.',
    // Missing string!!!
    'sun' => 'Sun',
    'sunday' => 'Sunday',
    // Missing string!!!
    'tab_default' => 'General',
    // Missing string!!!
    'the_password_should_at_least_contain_%d_%s' => 'The password should at least contain %d %s.',
    // Missing string!!!
    'the_password_should_be_at_least_%d_characters_long' => 'The password should be at least %d characters long.',
    // Missing string!!!
    'thousands_separator' => ',',
    // Missing string!!!
    'thu' => 'Thu',
    'thursday' => 'Thursday',
    // Missing string!!!
    'timezone_utc_+0000' => '(UTC) Casablanca, Greenwich Mean Time, London',
    // Missing string!!!
    'timezone_utc_+0100' => '(UTC+01:00) Amsterdam, Berlin, Rome, Paris',
    // Missing string!!!
    'timezone_utc_+0200' => '(UTC+02:00) Athens, Beirut, Istanbul, Minsk',
    // Missing string!!!
    'timezone_utc_+0300' => '(UTC+03:00) Baghdad, Kuwait, Riyadh, Moscow',
    // Missing string!!!
    'timezone_utc_+0400' => '(UTC+04:00) Abu Dhabi, Kabul',
    // Missing string!!!
    'timezone_utc_+0500' => '(UTC+05:00) New Delhi, Mumbai, Kathmandu',
    // Missing string!!!
    'timezone_utc_+0600' => '(UTC+06:00) Novosibirsk, Dhaka, Sri Jayawardenepura',
    // Missing string!!!
    'timezone_utc_+0700' => '(UTC+07:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk',
    // Missing string!!!
    'timezone_utc_+0800' => '(UTC+08:00) Beijing, Hong Kong, Ulaan Bataar',
    // Missing string!!!
    'timezone_utc_+0900' => '(UTC+09:00) Osaka, Sapporo, Tokyo, Seoul',
    // Missing string!!!
    'timezone_utc_+1000' => '(UTC+10:00) Brisbane, Melbourne, Sydney',
    // Missing string!!!
    'timezone_utc_+1100' => '(UTC+11:00) Solomon Is., Magadan',
    // Missing string!!!
    'timezone_utc_+1200' => '(UTC+12:00) Auckland, Wellington, Fiji',
    // Missing string!!!
    'timezone_utc_+1300' => "(UTC+13:00) Nuku'alofa",
    // Missing string!!!
    'timezone_utc_-0100' => '(UTC-01:00) Azores, Cape Verde Is.',
    // Missing string!!!
    'timezone_utc_-0200' => '(UTC-02:00) Mid-Atlantic',
    // Missing string!!!
    'timezone_utc_-0300' => '(UTC-03:00) Brasilia, Buenos Aires, Greenland',
    // Missing string!!!
    'timezone_utc_-0400' => '(UTC-04:00) Atlantic Time (Canada), Santiago',
    // Missing string!!!
    'timezone_utc_-0500' => '(UTC-05:00) Bogota, Lima, Quito, Eastern Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0600' => '(UTC-06:00) Central America, Central Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0700' => '(UTC-07:00) Arizona, Mountain Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0800' => '(UTC-08:00) Pacific Time (US & Canada); Tijuna',
    // Missing string!!!
    'timezone_utc_-0900' => '(UTC-09:00) Alaska',
    // Missing string!!!
    'timezone_utc_-1000' => '(UTC-10:00) Hawaii',
    // Missing string!!!
    'timezone_utc_-1100' => '(UTC-11:00) Midway Island, Samoa',
    // Missing string!!!
    'timezone_utc_-1200' => '(UTC-12:00) International Date Line West',
    // Missing string!!!
    'title_delete' => 'Vahvista poisto',
    'title_multiselect' => 'Multiselect',
    // Missing string!!!
    'title_select' => 'Select',
    // Missing string!!!
    'title_session_expired' => 'Session expired',
    // Missing string!!!
    'today' => 'Today',
    // Missing string!!!
    'tue' => 'Tue',
    'tuesday' => 'Tuesday',
    // Missing string!!!
    'unknown_error' => 'Unknown error',
    // Missing string!!!
    'unselect' => 'Deselect',
    // Missing string!!!
    'until' => 'until',
    'update' => 'Update',
    // Missing string!!!
    'upperchars' => 'uppercase characters',
    // Missing string!!!
    'username' => 'Username',
    'view' => 'Näytä',
    'view_all' => 'View all',
    // Missing string!!!
    'wed' => 'Wed',
    'wednesday' => 'Wednesday',
    // Missing string!!!
    'with_selected' => 'With selected',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'yes' => 'Kyllä',
];
