<?php
// Achievo language file for Polish.
// Generated by Achievo Translation Tool (20100804).
//
// Module: atk
// Language: Polish (pl)
//
// Translated by:
//   See doc/AUTHORS
//
// If you want to add a new language to achievo, please translate this
// file and send it to translations@achievo.org
//
// To update an existing translation, mail an updated version to
// translations@achievo.org or request an account for the Achievo
// Translation Tool.
//
return [
    'above_maximum_value' => 'Above the maximum allowed value',
    // Missing string!!!
    'access_denied' => 'Dostęp zabroniony',
    'add' => 'Dodaj',
    // Missing string!!!
    'add_criterium' => 'Add',
    // Missing string!!!
    'admin' => 'Zarządzaj',
    // Missing string!!!
    'all' => 'All',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'app_description' => 'Witaj w aplikacji ATK.',
    // Missing string!!!
    // Missing string!!!
    'app_shorttitle' => 'ATKApp',
    'app_title' => 'Aplikacja ATK',
    'apr' => 'Apr',
    // Missing string!!!
    'april' => 'Kwiecień',
    // Missing string!!!
    'attrib_delete_not_allowed' => "Field '%s' does not allow the record to be deleted. (%s)'",
    // Missing string!!!
    'aug' => 'Aug',
    // Missing string!!!
    'august' => 'Sierpień',
    'auth_account_locked' => 'Konto zostało zablokowane. Spróbuj uzyć innej nazwy użytkownika lub skontaktuj się z administratorem systemu.',
    'auth_max_loginattempts_exceeded' => 'Za dużo nieudanych prób logowania. Logowanie zostało zablokowane. Skontaktuj się z administratorem systemu.',
    'auth_mismatch' => 'Niepoprawna nazwa uzytkownika lub hasło. Spróbuj ponownie.',
    'auth_missingusername' => 'Please enter a username first.',
    // Missing string!!!
    'auth_no_server' => 'Nie podano serwera. Autoryzacja niemożliwa (skontaktuj się z administratorem systemu).',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'auth_unable_to_connect' => 'Nie można połaczyć sie z serwerem w celu autoryzacji (skontaktuj się z administratorem systemu).',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'available' => 'Available',
    // Missing string!!!
    'back' => 'Wróć',
    // Missing string!!!
    'cancel' => 'Anuluj',
    'cancel_edit' => 'Cancel edit',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'charset' => 'UTF-8',
    // Missing string!!!
    'check_all' => 'Zaznacz wszystkie',
    'check_none' => 'Odznacz wszystkie',
    'close' => 'Zamknij',
    // Missing string!!!
    'column' => 'column',
    // Missing string!!!
    'column_asc' => 'Up',
    // Missing string!!!
    'column_desc' => 'Down',
    // Missing string!!!
    'column_subtotal' => 'Subtotal',
    // Missing string!!!
    'column_unsubtotal' => 'No Subt.',
    // Missing string!!!
    'confirm_delete' => 'Czy jesteś pewien, że chcesz usunąć tę pozycję?',
    // Missing string!!!
    'copy' => 'Kopiuj',
    'criterium_field' => 'Field',
    // Missing string!!!
    'criterium_mode' => 'Mode',
    // Missing string!!!
    'criterium_value' => 'Value',
    // Missing string!!!
    'critical' => 'Critical',
    // Missing string!!!
    'datagrid_norecordsfound_general' => 'No records found.',
    // Missing string!!!
    'datagrid_norecordsfound_search' => 'No results found for the current search query.',
    // Missing string!!!
    'datagrid_summary' => '(Records [start] - [end] of [count])',
    // Missing string!!!
    'date_format_edit' => 'j F Y',
    // Missing string!!!
    'date_format_view' => 'j F Y',
    // Missing string!!!
    'db_access_denied_database' => "User '%s' has no rights for database '%s'",
    // Missing string!!!
    'db_access_denied_user' => "User'%s' can't connect with database '%s'",
    // Missing string!!!
    'db_unknown_database' => "Can't connect to database '%s'",
    // Missing string!!!
    'db_unknown_host' => "Can't find host '%s'",
    // Missing string!!!
    'dec' => 'Dec',
    // Missing string!!!
    'december' => 'Grudzień',
    'decimal_separator' => '.',
    // Missing string!!!
    'delete' => 'Usuń',
    'delimiter' => 'Delimiter',
    // Missing string!!!
    'deselect_all' => 'Odznacz wszystkie',
    // Missing string!!!
    'edit' => 'Edytuj',
    'editcopy' => 'Edytuj kopię',
    'email' => 'E-mail',
    // Missing string!!!
    'enclosure' => 'Enclosure',
    // Missing string!!!
    'error' => 'Błąd',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'error_date_invalid' => 'Invalid date',
    // Missing string!!!
    // Missing string!!!
    'error_file_mime_type' => 'Unsupported file uploaded please check your filetype or extension',
    // Missing string!!!
    'error_file_size' => 'File is too big',
    // Missing string!!!
    'error_file_unknown' => 'Unknown error during upload of file',
    // Missing string!!!
    'error_format_mismatch' => 'The element at position %d does not match the desired format (%s)',
    // Missing string!!!
    'error_formdataerror' => 'Zapisanie nie powiodło się: ',
    'error_iconv_not_install' => "iconv module don't install in your system, but it needs for right functionality",
    // Missing string!!!
    'error_invalid_email' => 'Niewłaściwy adres e-mail',
    'error_node_action_access_denied' => 'Nie masz uprawnień do wykonania tej operacji.',
    'error_notnumeric' => 'Podana wartość nie jest liczbą',
    'error_not_a_valid_ip' => 'This is not a valid IP address. An IP address consists of 4 numbers between 0 and 255.',
    // Missing string!!!
    'error_obligatoryfield' => 'to pole jest wymagane.',
    'error_password_incorrect' => 'The password you entered is incorrect!',
    // Missing string!!!
    // Missing string!!!
    'error_password_nomatch' => 'Wprowadzone nowe hasła nie są takie same.',
    'error_primarykey_exists' => 'Wpis z podanym kluczem już istnieje',
    'error_tab' => 'zobacz',
    // Missing string!!!
    'error_uniquefield' => 'Wartość w tym polu musi być unikalna',
    'error_uniquefieldset' => 'The values for the combination of these fields must be unique',
    // Missing string!!!
    'error_unkown_domain' => 'Nieznana domena',
    'explain_session_expired' => 'Czas Twojej sesji został przekroczony. Zdarzenie to występuje gdy aplikacja nie była przez pewien czas używana. Zaloguj się ponownie aby kontynuować pracę.',
    'export' => 'Eksport',
    'export_config_explanation' => 'Please select the options for the CSV export.',
    // Missing string!!!
    'export_generatetitlerow' => 'Include a title row',
    // Missing string!!!
    'export_selectcolumns' => 'Select which columns to export',
    // Missing string!!!
    'export_selections' => 'Standard selections',
    // Missing string!!!
    'export_selections_name' => 'Standard selections name',
    // Missing string!!!
    'feb' => 'Feb',
    // Missing string!!!
    'february' => 'Luty',
    'feedback' => 'Zadaj pytanie',
    'feedback_delete_cancelled' => 'The item has not been deleted.',
    // Missing string!!!
    'feedback_delete_failed' => 'The item could not be deleted.',
    // Missing string!!!
    'feedback_delete_success' => 'The item has been deleted.',
    // Missing string!!!
    'feedback_edit_failed' => "Editing is not possible. Item doesn\'t exist (anymore).",
    // Missing string!!!
    'feedback_import_failed' => 'File can not be imported',
    // Missing string!!!
    'feedback_save_cancelled' => 'The item has not been added.',
    // Missing string!!!
    'feedback_save_failed' => 'The item could not be added.',
    // Missing string!!!
    'feedback_save_success' => 'The item has been added.',
    // Missing string!!!
    'feedback_update_cancelled' => 'Changes have not been saved.',
    // Missing string!!!
    'feedback_update_failed' => 'The changes could not be saved.',
    // Missing string!!!
    'feedback_update_success' => 'The changes have been saved.',
    // Missing string!!!
    'filecontent' => 'Zawartość',
    'filename' => 'Nazwa pliku',
    'filename_invalid' => 'Podana nazwa pliku jest niewłaściwa',
    'file_exists' => 'Plik o podanej nazwie już istnieje',
    'file_not_exist' => 'Plik nie istnieje',
    // Missing string!!!
    'forget_criteria' => 'Remove selected search',
    // Missing string!!!
    'fri' => 'Pią',
    'friday' => 'Friday',
    // Missing string!!!
    'fsa_pleasemakeselection' => 'Znaleziono kilka wyników. Wybierz jeden.',
    'help' => 'Pomoc',
    'import' => 'Import data',
    // Missing string!!!
    'import_allfield' => 'Use default value for one of the attributes (e.g. if the column is absent in the CSV file)',
    // Missing string!!!
    'import_analyse' => 'Analyse again',
    // Missing string!!!
    'import_detectedcolumns' => 'Detected number of columns',
    // Missing string!!!
    'import_detectedrows' => 'Detected number of rows',
    // Missing string!!!
    'import_doupdate' => 'Try to update existing records',
    // Missing string!!!
    'import_error_allfieldnocorrectdata' => "The field for use in every record ('%s') does not contain valid data (%s)",
    // Missing string!!!
    'import_error_fieldisobligatory' => 'The following field should be mapped to a column',
    // Missing string!!!
    'import_error_fieldsareobligatory' => 'The following fields should be mapped to a column',
    // Missing string!!!
    'import_error_fieldsusedtwice' => 'The following fields are used more than once',
    // Missing string!!!
    'import_error_fieldusedtwice' => 'The following field is used more than once',
    // Missing string!!!
    'import_field' => 'Field',
    // Missing string!!!
    'import_ignorecolumn' => 'Ignore this column',
    // Missing string!!!
    'import_import' => 'Import',
    // Missing string!!!
    'import_importedreminder' => 'The file has already been imported, however there were errors detected in the following rows, these were not added/updated',
    // Missing string!!!
    'import_nonunique_identifier' => 'Non-unique identifier found in record where identier is %s',
    // Missing string!!!
    'import_onfalseidentifier' => 'Insert and continue in case of false identifier (2 records for the same key)',
    // Missing string!!!
    'import_relation_value_failed' => "Of the field '%s' has been found, on line %s, the value '%s', however this is not a unique value for this relation",
    // Missing string!!!
    'import_sample' => 'Sample from csv-file',
    // Missing string!!!
    'import_skipfirstrow' => 'Skip first line? (header row)',
    // Missing string!!!
    'import_update_key' => 'When updating, use this field to identify which record to update',
    // Missing string!!!
    'import_upload' => 'Upload',
    // Missing string!!!
    'import_upload_explanation' => 'Upload a textfile with data to import into the database.',
    // Missing string!!!
    'import_validatefirst' => 'Do not validate before importing',
    // Missing string!!!
    // Missing string!!!
    'invalid_relative_url' => "Invalid relative URL, please use this format: '/mysite/guestbook'",
    // Missing string!!!
    'invalid_url_anchor' => "Invalid URL anchor, please use this format: '#internal_bookmark'",
    // Missing string!!!
    'invert_selection' => 'Odwróć zaznaczenie',
    'in_use_by' => 'In use by',
    // Missing string!!!
    'jan' => 'Jan',
    // Missing string!!!
    'january' => 'Styczeń',
    'jul' => 'Jul',
    // Missing string!!!
    'july' => 'Lipiec',
    'jun' => 'Jun',
    // Missing string!!!
    'june' => 'Czerwiec',
    'language_de' => 'niemiecki',
    'language_en' => 'English',
    // Missing string!!!
    'language_fr' => 'French',
    // Missing string!!!
    'language_nl' => 'holenderski',
    'language_pl' => 'polski',
    'language_sp' => 'Spanish',
    // Missing string!!!
    'list_null_value' => 'No value',
    // Missing string!!!
    'list_null_value_obligatory' => '(Select a value...)',
    // Missing string!!!
    'load_criteria' => 'Load saved search',
    // Missing string!!!
    // Missing string!!!
    'lock_info_line' => '[user_id] (ip: [user_ip]) since [lock_date]',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'login' => 'Zaloguj',
    'login_form' => 'Logowanie',
    // Missing string!!!
    'lose_changes_warning' => 'If you navigate away from this page, all your changes will be lost.',
    // Missing string!!!
    // Missing string!!!
    'mar' => 'Mar',
    // Missing string!!!
    'march' => 'Marzec',
    'may' => 'Maj',
    'menu' => 'Menu',
    'menu_main' => 'Główne menu',
    'mon' => 'Pon',
    'monday' => 'Monday',
    // Missing string!!!
    // Missing string!!!
    'new' => 'New',
    // Missing string!!!
    'next' => 'Następne',
    'no' => 'Nie',
    'none' => 'None',
    // Missing string!!!
    'nov' => 'Nov',
    // Missing string!!!
    'november' => 'Listopad',
    // Missing string!!!
    // Missing string!!!
    'no_records_to_import' => 'No records found that needed to be imported.',
    // Missing string!!!
    'no_results_found' => 'No results found',
    // Missing string!!!
    'no_valid_directory' => 'Niepoprawny katalog',
    'numbers' => 'numbers',
    // Missing string!!!
    'oct' => 'Oct',
    // Missing string!!!
    'october' => 'Październik',
    'open' => 'Open',
    // Missing string!!!
    'or' => 'Or',
    // Missing string!!!
    'password' => 'Hasło',
    'password_again' => 'Ponownie',
    'password_current' => 'Bieżące',
    // Missing string!!!
    'password_hidden' => '*****',
    'password_incorrect' => 'Niepoprawne stare hasło. Brak dostępu!',
    'password_new' => 'Nowe',
    'recordlistsummary' => 'Record [start]-[end] out of [count]',
    // Missing string!!!
    'relogin' => 'Log in again',
    // Missing string!!!
    'remove_criterium' => 'Remove',
    // Missing string!!!
    'remove_current_file' => 'Usuń bieżący plik',
    // Missing string!!!
    'reset_criteria' => 'New search',
    // Missing string!!!
    'restricted_delete_error' => 'There is detail information below this record that needs to be deleted first.',
    // Missing string!!!
    'sat' => 'Sob',
    'saturday' => 'Saturday',
    // Missing string!!!
    'save' => 'Zapisz',
    'saveandaddnew' => 'Save and add new',
    // Missing string!!!
    'saveandclose' => 'Zapisz i zamknij',
    'saveandedit' => 'Save and edit',
    // Missing string!!!
    'saveandnext' => 'Save and next',
    // Missing string!!!
    'save_criteria' => 'Save search as',
    // Missing string!!!
    'save_export_selection' => 'Save selection',
    // Missing string!!!
    'search' => 'Szukaj',
    'search_all' => ' ',
    // I don't like it. Empty drop down box is more intuitive for me. Otherwise "Szukaj we wszystkich" was ok.",
    'search_and' => 'Match all criteria',
    // Missing string!!!
    'search_between' => 'Search between two values',
    // Missing string!!!
    'search_exact' => 'Szukaj podanej frazy tak jak wpisano',
    'search_extended' => 'Rozszerzone',
    'search_greaterthan' => 'Search for value bigger than',
    // Missing string!!!
    'search_greaterthanequal' => 'Search for value bigger than or equal to',
    // Missing string!!!
    'search_lessthan' => 'Search for value smaller than',
    // Missing string!!!
    'search_lessthanequal' => 'Search for value smaller than or equal to',
    // Missing string!!!
    'search_mode' => 'Tryb wyszukiwania',
    'search_none' => 'Nothing selected',
    // Missing string!!!
    'search_or' => 'Match any criteria',
    // Missing string!!!
    'search_regexp' => 'Szukaj wg wyrażenia regularnego (zaawansowane)',
    'search_soundex' => 'Szukaj ciągu znaków który brzmi podobnie do',
    'search_substring' => 'Szukaj ciągu znaków',
    'search_wildcard' => 'Szukaj wg maski (*)',
    'select' => 'Wybierz',
    'selected' => 'Selected',
    // Missing string!!!
    'selection' => 'Selection',
    // Missing string!!!
    'select_a' => 'Select',
    // Missing string!!!
    'select_all' => 'Zaznacz wszystkie',
    'select_invert' => 'Odwróć zaznaczenie',
    'select_none' => 'brak',
    'self' => 'Self',
    // Missing string!!!
    'sep' => 'Sep',
    // Missing string!!!
    'september' => 'Wrzesień',
    'settings' => 'Settings',
    // Missing string!!!
    'show' => 'Show',
    // Missing string!!!
    'smartsearch' => 'Smart search',
    // Missing string!!!
    'sort' => 'Sort',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'submit' => 'Zatwierdź',
    'successfully_imported_one_record' => 'Successfully imported 1 record.',
    // Missing string!!!
    'successfully_imported_x_records' => 'Successfully imported %d records.',
    // Missing string!!!
    'sun' => 'Nie',
    'sunday' => 'Sunday',
    // Missing string!!!
    'tab_default' => 'General',
    // Missing string!!!
    'the_password_should_at_least_contain_%d_%s' => 'The password should at least contain %d %s.',
    // Missing string!!!
    'the_password_should_be_at_least_%d_characters_long' => 'The password should be at least %d characters long.',
    // Missing string!!!
    'thousands_separator' => ',',
    // Missing string!!!
    'thu' => 'Czw',
    'thursday' => 'Thursday',
    // Missing string!!!
    'timezone_utc_+0000' => '(UTC) Casablanca, Greenwich Mean Time, London',
    // Missing string!!!
    'timezone_utc_+0100' => '(UTC+01:00) Amsterdam, Berlin, Rome, Paris',
    // Missing string!!!
    'timezone_utc_+0200' => '(UTC+02:00) Athens, Beirut, Istanbul, Minsk',
    // Missing string!!!
    'timezone_utc_+0300' => '(UTC+03:00) Baghdad, Kuwait, Riyadh, Moscow',
    // Missing string!!!
    'timezone_utc_+0400' => '(UTC+04:00) Abu Dhabi, Kabul',
    // Missing string!!!
    'timezone_utc_+0500' => '(UTC+05:00) New Delhi, Mumbai, Kathmandu',
    // Missing string!!!
    'timezone_utc_+0600' => '(UTC+06:00) Novosibirsk, Dhaka, Sri Jayawardenepura',
    // Missing string!!!
    'timezone_utc_+0700' => '(UTC+07:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk',
    // Missing string!!!
    'timezone_utc_+0800' => '(UTC+08:00) Beijing, Hong Kong, Ulaan Bataar',
    // Missing string!!!
    'timezone_utc_+0900' => '(UTC+09:00) Osaka, Sapporo, Tokyo, Seoul',
    // Missing string!!!
    'timezone_utc_+1000' => '(UTC+10:00) Brisbane, Melbourne, Sydney',
    // Missing string!!!
    'timezone_utc_+1100' => '(UTC+11:00) Solomon Is., Magadan',
    // Missing string!!!
    'timezone_utc_+1200' => '(UTC+12:00) Auckland, Wellington, Fiji',
    // Missing string!!!
    'timezone_utc_+1300' => "(UTC+13:00) Nuku'alofa",
    // Missing string!!!
    'timezone_utc_-0100' => '(UTC-01:00) Azores, Cape Verde Is.',
    // Missing string!!!
    'timezone_utc_-0200' => '(UTC-02:00) Mid-Atlantic',
    // Missing string!!!
    'timezone_utc_-0300' => '(UTC-03:00) Brasilia, Buenos Aires, Greenland',
    // Missing string!!!
    'timezone_utc_-0400' => '(UTC-04:00) Atlantic Time (Canada), Santiago',
    // Missing string!!!
    'timezone_utc_-0500' => '(UTC-05:00) Bogota, Lima, Quito, Eastern Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0600' => '(UTC-06:00) Central America, Central Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0700' => '(UTC-07:00) Arizona, Mountain Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0800' => '(UTC-08:00) Pacific Time (US & Canada); Tijuna',
    // Missing string!!!
    'timezone_utc_-0900' => '(UTC-09:00) Alaska',
    // Missing string!!!
    'timezone_utc_-1000' => '(UTC-10:00) Hawaii',
    // Missing string!!!
    'timezone_utc_-1100' => '(UTC-11:00) Midway Island, Samoa',
    // Missing string!!!
    'timezone_utc_-1200' => '(UTC-12:00) International Date Line West',
    // Missing string!!!
    'title_delete' => 'Potwierdź usunięcie',
    'title_multiselect' => 'Multiselect',
    // Missing string!!!
    'title_select' => 'Select',
    // Missing string!!!
    'title_session_expired' => 'Czas sesji został przekroczony',
    // Missing string!!!
    'today' => 'Today',
    // Missing string!!!
    'tue' => 'Wto',
    'tuesday' => 'Tuesday',
    // Missing string!!!
    'unknown_error' => 'Unknown error',
    // Missing string!!!
    'unselect' => 'Deselect',
    // Missing string!!!
    'until' => 'do',
    'update' => 'Update',
    // Missing string!!!
    'upperchars' => 'uppercase characters',
    // Missing string!!!
    'username' => 'Użytkownik',
    'view' => 'Pokaż',
    'view_all' => 'View all',
    // Missing string!!!
    'wed' => 'Śro',
    'wednesday' => 'Wednesday',
    // Missing string!!!
    'with_selected' => 'Dla zaznaczonych',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'yes' => 'Tak',
];
