<?php
// Achievo language file for Swedish.
// Generated by Achievo Translation Tool (20100804).
//
// Module: atk
// Language: Swedish (sv)
//
// Translated by:
//   See doc/AUTHORS
//
// If you want to add a new language to achievo, please translate this
// file and send it to translations@achievo.org
//
// To update an existing translation, mail an updated version to
// translations@achievo.org or request an account for the Achievo
// Translation Tool.
//
return [
    'above_maximum_value' => 'Över max tillåtet värde',
    'access_denied' => 'Nekad åtkomst',
    'add' => 'Lägg till',
    // Missing string!!!
    'add_criterium' => 'Add',
    // Missing string!!!
    'admin' => 'Administration',
    'all' => 'All',
    // Missing string!!!
    // Missing string!!!
    'app_description' => 'Välkommer till denna ATK-applikation.',
    'app_shorttitle' => 'ATKApp',
    'app_title' => 'ATK-Applikation',
    'apr' => 'Apr',
    'april' => 'April',
    // Missing string!!!
    'attrib_delete_not_allowed' => "Fältet '%s' tillåter inte att posten raderas. '(%s)'",
    'aug' => 'Aug',
    'august' => 'Augusti',
    'auth_account_locked' => 'Kontot har blivit låst. Prova ett annat konto eller kontakta din systemadministratör.',
    'auth_max_loginattempts_exceeded' => 'För många försök. Inloggningen har stängs av. Kontakta din systemadministratör.',
    'auth_mismatch' => 'Användarnamn och/eller lösenord är fel. Försök igen.',
    'auth_missingusername' => 'Please enter a username first.',
    // Missing string!!!
    'auth_no_server' => 'Ingen server specificerad. Ingen autenticering är möjlig (kontakta systemadministratören).',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'auth_unable_to_connect' => 'Kunde inte kontakta server för autenticering (kontakta systemadministratören).',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'available' => 'Available',
    // Missing string!!!
    'back' => 'Tillbaka',
    'cancel' => 'Avbryt',
    'cancel_edit' => 'Cancel edit',
    // Missing string!!!
    // Missing string!!!
    'charset' => 'UTF-8',
    'check_all' => 'Välj alla',
    'check_none' => 'Välj ingen',
    'close' => 'Stäng',
    // Missing string!!!
    'column' => 'kolumn',
    'column_asc' => 'Upp',
    'column_desc' => 'Ner',
    'column_subtotal' => 'Deltotal',
    'column_unsubtotal' => 'Ingen deltot.',
    'confirm_delete' => 'Vill du verligen radera denna post?',
    // Missing string!!!
    'copy' => 'Kopiera',
    'criterium_field' => 'Field',
    // Missing string!!!
    'criterium_mode' => 'Mode',
    // Missing string!!!
    'criterium_value' => 'Value',
    // Missing string!!!
    'critical' => 'Kritiska',
    'datagrid_norecordsfound_general' => 'No records found.',
    // Missing string!!!
    'datagrid_norecordsfound_search' => 'No results found for the current search query.',
    // Missing string!!!
    'datagrid_summary' => '(Records [start] - [end] of [count])',
    // Missing string!!!
    'date_format_edit' => 'j F Y',
    'date_format_view' => 'j F Y',
    'db_access_denied_database' => "Användare '%s' har inga rättigheter för databasen '%s'",
    'db_access_denied_user' => "Användare '%s' kan inte kontakta databasen '%s'",
    'db_unknown_database' => "Kan inte kontakta databasen '%s'",
    'db_unknown_host' => "Kan inte hitta dator '%s'",
    'dec' => 'Dec',
    'december' => 'December',
    'decimal_separator' => '.',
    'delete' => 'Radera',
    'delimiter' => 'Delimiter',
    // Missing string!!!
    'deselect_all' => 'Avmarkera allt',
    // Missing string!!!
    'edit' => 'Ändra',
    'editcopy' => 'Ändra kopia',
    'email' => 'E-mail',
    // Missing string!!!
    'enclosure' => 'Enclosure',
    // Missing string!!!
    'error' => 'Fel',
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    // Missing string!!!
    'error_date_invalid' => 'Felaktigt datum',
    'error_file_mime_type' => 'Unsupported file uploaded please check your filetype or extension',
    // Missing string!!!
    'error_file_size' => 'Filen är för stor',
    'error_file_unknown' => 'Okänt fel vid uppladdning av fil',
    'error_format_mismatch' => 'Elementet vid position %d stämmer inte med begärt format',
    'error_formdataerror' => 'Sparandet misslyckades pga följande fel: ',
    'error_iconv_not_install' => "iconv module don't install in your system, but it needs for right functionality",
    // Missing string!!!
    'error_invalid_email' => 'Felaktig epostadress',
    'error_node_action_access_denied' => 'Ledsen, men du har inte rättigheter att göra detta.',
    'error_notnumeric' => 'Värdet är inte numeriskt',
    'error_not_a_valid_ip' => 'This is not a valid IP address. An IP address consists of 4 numbers between 0 and 255.',
    // Missing string!!!
    'error_obligatoryfield' => 'Detta fält krävs',
    'error_password_incorrect' => 'Lösenordet du matade in är fel!',
    'error_password_nomatch' => 'Medskickat lösenord stämmer inte.',
    'error_primarykey_exists' => 'En post med denna nyckel finns redan',
    'error_tab' => 'se',
    // Missing string!!!
    'error_uniquefield' => 'Värdet i detta fält måse vara unikt',
    'error_uniquefieldset' => 'Värdeskombinationen för dessa fält måste vara unik',
    'error_unkown_domain' => 'Okänd domän',
    'explain_session_expired' => 'Din session har gått ut. Detta händer om programmet är inaktivt under en viss tid. Du kan fortsätta genom att logga in igen.',
    'export' => 'Exportera',
    'export_config_explanation' => 'Välj inställningar för CSV-exporten.',
    'export_generatetitlerow' => 'Inkludera en titelrad',
    'export_selectcolumns' => 'Välj kolumner att exportera',
    'export_selections' => 'Standard selections',
    // Missing string!!!
    'export_selections_name' => 'Standard selections name',
    // Missing string!!!
    'feb' => 'Feb',
    'february' => 'Februari',
    'feedback' => 'Feedback',
    'feedback_delete_cancelled' => 'Posten har inte raderats.',
    'feedback_delete_failed' => 'Posten kunde inte raderas.',
    'feedback_delete_success' => 'Posten har raderats.',
    'feedback_edit_failed' => "Editing is not possible. Item doesn\'t exist (anymore).",
    // Missing string!!!
    'feedback_import_failed' => 'Filen kunde inte importeras',
    'feedback_save_cancelled' => 'Posten har inte lagts till.',
    'feedback_save_failed' => 'Posten har inte lagts till.',
    'feedback_save_success' => 'Posten har lagts till.',
    'feedback_update_cancelled' => 'Ändringarna har inte sparats.',
    'feedback_update_failed' => 'Ändringarna kunde inte sparas.',
    'feedback_update_success' => 'Ändringarna har sparats.',
    'filecontent' => 'Innehåll',
    'filename' => 'Filnamn',
    'filename_invalid' => 'Filnamnet är felaktigt',
    'file_exists' => 'En fil med detta namn finns redan',
    'file_not_exist' => 'Filen finns inte',
    // Missing string!!!
    'forget_criteria' => 'Remove selected search',
    // Missing string!!!
    'fri' => 'Fre',
    'friday' => 'Fredag',
    'fsa_pleasemakeselection' => 'Mer än en träff hittades. Välj en.',
    'help' => 'Hjälp',
    'import' => 'Importera data',
    'import_allfield' => 'Använd standardvärde för ett av attributen (t ex om kolumnen inte finns i CSV-filen)',
    'import_analyse' => 'Analysera igen',
    'import_detectedcolumns' => 'Hittade kolumner',
    'import_detectedrows' => 'Antal hittade rader',
    'import_doupdate' => 'Försöker uppdatera befintliga poster',
    'import_error_allfieldnocorrectdata' => 'Fältet som används i varje post innehåller ingen korrekt data',
    'import_error_fieldisobligatory' => 'Nästa fält är obligatoriskt och borde innehålla data',
    'import_error_fieldsareobligatory' => 'Nästkommande fält är obligatoriska och borde innehålla data',
    'import_error_fieldsusedtwice' => 'Nästa fält används två gånger',
    'import_error_fieldusedtwice' => 'Nästa fält används två gånger',
    'import_field' => 'Fält',
    'import_ignorecolumn' => 'Ignorera denna kolumn',
    'import_import' => 'Importera',
    'import_importedreminder' => 'Filen har redan importerats, men det fanns fel på följande rader och dessa blev inte sparade/uppdaterade',
    'import_nonunique_identifier' => 'Icke-unik identifierare hittades i posten med id %s',
    'import_onfalseidentifier' => 'Lägg till och fortsätt ifall en falsk identifierare (2 poster med samma nyckel)',
    'import_relation_value_failed' => "I fältet '%s' hittades på rad %s värdet %s, men detta är inte ett unikt värde för denna relation",
    'import_sample' => 'Exempel från csv-fil',
    'import_skipfirstrow' => 'Strunta i första raden? (etikettraden)',
    'import_update_key' => 'Vid uppdatering, använd detta fält för att identifiera poster',
    'import_upload' => 'Ladda upp',
    'import_upload_explanation' => 'Ladda upp en textfil med data för import till databas.',
    'import_validatefirst' => 'Validera inte före import',
    // Missing string!!!
    'invalid_relative_url' => "Invalid relative URL, please use this format: '/mysite/guestbook'",
    // Missing string!!!
    'invalid_url_anchor' => "Invalid URL anchor, please use this format: '#internal_bookmark'",
    // Missing string!!!
    'invert_selection' => 'Invertera markering',
    'in_use_by' => 'In use by',
    // Missing string!!!
    'jan' => 'Jan',
    'january' => 'Januari',
    'jul' => 'Jul',
    'july' => 'Juli',
    'jun' => 'Jun',
    'june' => 'Juni',
    'language_de' => 'Tyska',
    'language_en' => 'Engelska',
    'language_fr' => 'Franska',
    'language_nl' => 'Holländska',
    'language_pl' => 'Polish',
    // Missing string!!!
    'language_sp' => 'Spanish',
    // Missing string!!!
    'list_null_value' => 'Inget värde',
    'list_null_value_obligatory' => '(Select a value...)',
    // Missing string!!!
    'load_criteria' => 'Load saved search',
    // Missing string!!!
    'lock_info_line' => '[user_id] (ip: [user_ip]) since [lock_date]',
    // Missing string!!!
    'login' => 'Logga in',
    'login_form' => 'Logga in',
    'lose_changes_warning' => 'If you navigate away from this page, all your changes will be lost.',
    // Missing string!!!
    // Missing string!!!
    'mar' => 'Mar',
    'march' => 'Mars',
    'may' => 'Maj',
    'menu' => 'Meny',
    'menu_main' => 'Huvudmeny',
    'mon' => 'Mån',
    'monday' => 'Måndag',
    // Missing string!!!
    'new' => 'Ny',
    'next' => 'Nästa',
    'no' => 'Nej',
    'none' => 'Ingen',
    'nov' => 'Nov',
    'november' => 'November',
    // Missing string!!!
    // Missing string!!!
    'no_records_to_import' => 'No records found that needed to be imported.',
    // Missing string!!!
    'no_results_found' => 'Inga resultat hittades',
    'no_valid_directory' => 'Det finns ingen giltig katalog',
    'numbers' => 'numbers',
    // Missing string!!!
    'oct' => 'Okt',
    'october' => 'Oktober',
    'open' => 'Öppna',
    'or' => 'Or',
    // Missing string!!!
    'password' => 'Lösenord',
    'password_again' => 'Nytt lösenord igen',
    'password_current' => 'Nuvarande lösenord',
    // Missing string!!!
    'password_hidden' => '*****',
    'password_incorrect' => 'Lösenordet du skrev var inte korrekt!',
    'password_new' => 'Nytt lösenord',
    'recordlistsummary' => 'Record [start]-[end] out of [count]',
    // Missing string!!!
    'relogin' => 'Logga in igen',
    'remove_criterium' => 'Remove',
    // Missing string!!!
    'remove_current_file' => 'Ta bort nuvarande fil',
    // Missing string!!!
    'reset_criteria' => 'New search',
    // Missing string!!!
    'restricted_delete_error' => 'Det finns detaljinformation under denna post som måste raderas först.',
    'sat' => 'Lör',
    'saturday' => 'Lördag',
    'save' => 'Spara',
    'saveandaddnew' => 'Save and add new',
    // Missing string!!!
    'saveandclose' => 'Spara och stäng',
    'saveandedit' => 'Save and edit',
    // Missing string!!!
    'saveandnext' => 'Spara och nästa',
    'save_criteria' => 'Save search as',
    // Missing string!!!
    'save_export_selection' => 'Save selection',
    // Missing string!!!
    'search' => 'Sök',
    'search_all' => 'Sök alla',
    'search_and' => 'Träffa alla kriterier',
    'search_between' => 'Sök mellan två värden',
    'search_exact' => 'Sök efter en exakt träff',
    'search_extended' => 'Utökad',
    'search_greaterthan' => 'Sök efter ett värde större än',
    'search_greaterthanequal' => 'Sök efter ett värde större eller lika med',
    'search_lessthan' => 'Sök efter ett värde mindre än',
    'search_lessthanequal' => 'Sök efter ett värde mindre eller lika med',
    'search_mode' => 'Sökläge',
    'search_none' => 'Nothing selected',
    // Missing string!!!
    'search_or' => 'Träffa vilken kritera som helst',
    'search_regexp' => 'Sök med reguljära uttryck (avancerat)',
    'search_soundex' => 'Sök efter text som låter liknande',
    'search_substring' => 'Sök efter en delsträng',
    'search_wildcard' => 'Sök med wildcards (*)',
    'select' => 'Välj',
    'selected' => 'Selected',
    // Missing string!!!
    'selection' => 'Val',
    'select_a' => 'Välj en',
    'select_all' => 'Välj alla',
    'select_invert' => 'Invertera val',
    'select_none' => 'Ingen',
    'self' => 'Self',
    // Missing string!!!
    'sep' => 'Sep',
    'september' => 'September',
    'settings' => 'Inställningar',
    'show' => 'Show',
    // Missing string!!!
    'smartsearch' => 'Smart search',
    // Missing string!!!
    'sort' => 'Sortera',
    // Missing string!!!
    // Missing string!!!
    'submit' => 'Ok',
    'successfully_imported_one_record' => 'Successfully imported 1 record.',
    // Missing string!!!
    'successfully_imported_x_records' => 'Successfully imported %d records.',
    // Missing string!!!
    'sun' => 'Sön',
    'sunday' => 'Söndag',
    'tab_default' => 'Generellt',
    'the_password_should_at_least_contain_%d_%s' => 'The password should at least contain %d %s.',
    // Missing string!!!
    'the_password_should_be_at_least_%d_characters_long' => 'The password should be at least %d characters long.',
    // Missing string!!!
    'thousands_separator' => ',',
    'thu' => 'Tor',
    'thursday' => 'Torsdag',
    'timezone_utc_+0000' => '(UTC) Casablanca, Greenwich Mean Time, London',
    // Missing string!!!
    'timezone_utc_+0100' => '(UTC+01:00) Amsterdam, Berlin, Rome, Paris',
    // Missing string!!!
    'timezone_utc_+0200' => '(UTC+02:00) Athens, Beirut, Istanbul, Minsk',
    // Missing string!!!
    'timezone_utc_+0300' => '(UTC+03:00) Baghdad, Kuwait, Riyadh, Moscow',
    // Missing string!!!
    'timezone_utc_+0400' => '(UTC+04:00) Abu Dhabi, Kabul',
    // Missing string!!!
    'timezone_utc_+0500' => '(UTC+05:00) New Delhi, Mumbai, Kathmandu',
    // Missing string!!!
    'timezone_utc_+0600' => '(UTC+06:00) Novosibirsk, Dhaka, Sri Jayawardenepura',
    // Missing string!!!
    'timezone_utc_+0700' => '(UTC+07:00) Bangkok, Hanoi, Jakarta, Krasnoyarsk',
    // Missing string!!!
    'timezone_utc_+0800' => '(UTC+08:00) Beijing, Hong Kong, Ulaan Bataar',
    // Missing string!!!
    'timezone_utc_+0900' => '(UTC+09:00) Osaka, Sapporo, Tokyo, Seoul',
    // Missing string!!!
    'timezone_utc_+1000' => '(UTC+10:00) Brisbane, Melbourne, Sydney',
    // Missing string!!!
    'timezone_utc_+1100' => '(UTC+11:00) Solomon Is., Magadan',
    // Missing string!!!
    'timezone_utc_+1200' => '(UTC+12:00) Auckland, Wellington, Fiji',
    // Missing string!!!
    'timezone_utc_+1300' => "(UTC+13:00) Nuku'alofa",
    // Missing string!!!
    'timezone_utc_-0100' => '(UTC-01:00) Azores, Cape Verde Is.',
    // Missing string!!!
    'timezone_utc_-0200' => '(UTC-02:00) Mid-Atlantic',
    // Missing string!!!
    'timezone_utc_-0300' => '(UTC-03:00) Brasilia, Buenos Aires, Greenland',
    // Missing string!!!
    'timezone_utc_-0400' => '(UTC-04:00) Atlantic Time (Canada), Santiago',
    // Missing string!!!
    'timezone_utc_-0500' => '(UTC-05:00) Bogota, Lima, Quito, Eastern Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0600' => '(UTC-06:00) Central America, Central Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0700' => '(UTC-07:00) Arizona, Mountain Time (US & Canada)',
    // Missing string!!!
    'timezone_utc_-0800' => '(UTC-08:00) Pacific Time (US & Canada); Tijuna',
    // Missing string!!!
    'timezone_utc_-0900' => '(UTC-09:00) Alaska',
    // Missing string!!!
    'timezone_utc_-1000' => '(UTC-10:00) Hawaii',
    // Missing string!!!
    'timezone_utc_-1100' => '(UTC-11:00) Midway Island, Samoa',
    // Missing string!!!
    'timezone_utc_-1200' => '(UTC-12:00) International Date Line West',
    // Missing string!!!
    'title_delete' => 'Godkänn radering',
    'title_multiselect' => 'Multiselect',
    // Missing string!!!
    'title_select' => 'Välj',
    'title_session_expired' => 'Sessionen föfallit',
    // Missing string!!!
    'today' => 'Idag',
    'tue' => 'Tis',
    'tuesday' => 'Tisdag',
    'unknown_error' => 'Okänt fel',
    'unselect' => 'Deselect',
    // Missing string!!!
    'until' => 'tills',
    'update' => 'Uppdatera',
    'upperchars' => 'uppercase characters',
    // Missing string!!!
    'username' => 'Användarnamn',
    'view' => 'Vy',
    'view_all' => 'Visa alla',
    'wed' => 'Ons',
    'wednesday' => 'Onsdag',
    'with_selected' => 'Med valda',
    'yes' => 'Ja',
];
