<?php

  // Default information
  $g_theme["Author"] = "Sandy Pleyte"; // Author name
  $g_theme["Author_email"] = "sandy@ibuildings.nl";  // Author e-mail
  $g_theme["Description"] = "Blue Blurb";  // Theme description
  $g_theme["Version"] = "1.5";  // version number
  
  // some picture urls
  $g_theme["BgURL"] = "";    // Background url
  $g_theme["LogoURLl"] = "";  // Logo url
  
  // Font settings
  $g_theme["FontFamily"] = "Arial,Helvetica"; // Font
  $g_theme["FontSize"] = "8"; // Font size in pt.
  $g_theme["FontWeight"] = "none"; 
  
  // Font settings for a block
  $g_theme["BlockFontFamily"] = "Arial,Helvetica"; // Font
  $g_theme["BlockFontSize"] = "12"; // Font size in pt.
  $g_theme["BlockFontWeight"] = "none"; // FontWeight (bold) 
  
  // Body settings
  $g_theme["BgColor"] = "#006699"; // Background color
  $g_theme["FgColor"] = "#000000"; // text color
  
  // Link settings
  $g_theme["LinkColor"] = "#000000"; // link color
  $g_theme["VisitedColor"] = "#000000"; // Visited color
  $g_theme["HoverColor"] = "#006699"; // Hover color (IE4 Only)
  $g_theme["ActiveColor"] = "#000000"; // Active color (IE4 Only)

  // Table header settings
  $g_theme["TableHeaderFontFamily"] = "Arial,Helvetica"; // Font
  $g_theme["TableHeaderFontSize"] = "12"; // Font size in pt.
  $g_theme["TableHeaderFontWeight"] = "Bold"; // FontWeight (bold) 
  $g_theme["TableHeaderBgColor"] = "#cccccc"; // Table bgcolor;
  $g_theme["TableHeaderFgColor"] = "#000000"; // Table font color;
 
  // Table settings
  $g_theme["TableFontFamily"] = "Arial,Helvetica"; // Font
  $g_theme["TableFontSize"] = "12"; // Font size in pt.
  $g_theme["TableFontWeight"] = "none"; // FontWeight (bold) 
  $g_theme["TableFgColor"] = "#000000"; // Table font color;
//$g_theme["TableBgColor"] = "#eeeeee"; // Table back color  disable if you want to use multiple colors in the rows;
  
// display settings 
  $g_theme["border"] = "1";
  $g_theme["BorderColor"] = "#000000";
  $g_theme["RowColor1"] ="#ffffff";
  $g_theme["RowColor2"] = "#eeeeee";
  $g_theme["RowMouseOver"] = "#ccffcc";
?>