<?php
  // Default information
  $g_theme["Author"] = "Sandy Pleyte"; // Author name
  $g_theme["Author_email"] = "sandy@ibuildings.nl";  // Author e-mail
  $g_theme["Description"] = "Newspapered";  // Theme description
  $g_theme["Version"] = "1.0";  // version number

  // some picture urls
  $g_theme["BgURL"] = "";    // Background url
  $g_theme["LogoURLl"] = "";  // Logo url

  // Font settings
  $g_theme["FontFamily"] = "Tahoma, Helvetica, Arial"; // Font
  $g_theme["FontSize"] = "8"; // Font size in pt.
  $g_theme["FontWeight"] = "none";
  
  // Font settings for a block
  $g_theme["BlockFontFamily"] = "Tahoma, Helvetica, Arial"; // Font
  $g_theme["BlockFontSize"] = "12"; // Font size in pt.
  $g_theme["BlockFontWeight"] = "none"; // FontWeight (bold)
  
  // Body settings
  $g_theme["BgColor"] = "#ffffff"; // Background color
  $g_theme["FgColor"] = "#000000"; // text color
  
  // Link settings
  $g_theme["LinkColor"] = "#000000"; // link color
  $g_theme["HoverColor"] = "#ff0000"; // Hover color
  $g_theme["VisitedColor"] = "#000000"; // Visited color
  $g_theme["ActiveColor"] = "#000000"; // Active color (IE4 Only)

  // Table header settings
  $g_theme["TableHeaderFontFamily"] = "Tahoma, Helvetica, Arial"; // Font
  $g_theme["TableHeaderFontSize"] = "12"; // Font size in pt.
  $g_theme["TableHeaderFontWeight"] = "Bold"; // FontWeight (bold) 
  $g_theme["TableHeaderBgColor"] = "#cccccc"; // Table bgcolor;
  $g_theme["TableHeaderFgColor"] = "#000000"; // Table font color;
 
  // Table settings
  $g_theme["TableFontFamily"] = "Tahoma, Helvetica, Arial"; // Font
  $g_theme["TableFontSize"] = "12"; // Font size in pt.
  $g_theme["TableFontWeight"] = "none"; // FontWeight (bold) 
  $g_theme["TableFgColor"] = "#000000"; // Table font color;


?>
