<?php

  $theme["customtpls"] = array("action.tpl","action_view.tpl","actionpage.tpl","box.tpl","editform.tpl","list.tpl","login.tpl","recordlist.tpl","searchform.tpl","statusbar.tpl","tabs.tpl","viewform.tpl");  
  $theme["customimgs"] = array("help.gif","hide_bg.gif","hide_explorer.gif", "menubanner.jpg", "menulogo.gif", "required_field.gif", "show_explorer.gif");
  $theme["customstyles"] = array("atkdateattribute.css","dhtml_dropdown.css","recordlist.css", "style.css", "tabs.css");
  
  $theme["recordlist_icons"] = array("copy.gif","default.gif","delete.gif","done.gif","edit.gif","export.gif","preview.gif","select.gif","view.gif");
  
  $theme["highlight"] = "#eeeeee";
  $theme["select"] = "#cccccc";
  
?>
