<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be
   * included in the distribution.
   *
   * @package atk
   * @subpackage themes
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision$
   * $Id$
   */

  /** Theme definition */
  $theme["highlight"] = "#eeeeee";
  $theme["select"] = "#cccccc";

  // Outlook style menu
  $theme["ol_menucolor"]="#ffffff";
  $theme["ol_wincolor"]="#eeeee0";
  $theme["ol_background"]="#677EB1";
  
  $theme["recordlist_orientation"]='left';
  $theme["recordlist_vorientation"]='top';
  $theme['recordlist_icons']=true;
  $theme['dialog_theme_name'] = 'alphacube';
  $theme['dialog_theme_load'] = true;
?>
